### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by eglassman** [andrewhead/examplify#3]
So, I got to this part of the README, and the following happened:

```
airbears2-10-142-37-169:examplify elenaglassman$ SOOT_JARS=`ls -d -1 $PWD/java/libs/*.jar | tr '\n' ':'`
airbears2-10-142-37-169:examplify elenaglassman$ JAVA_HOME_LIBS=`ls -d -1 $JAVA_HOME/jre/lib/*.jar | tr '\n' ':'`
ls: /jre/lib/*.jar: No such file or directory
airbears2-10-142-37-169:examplify elenaglassman$ cd java/
airbears2-10-142-37-169:java elenaglassman$ javac -cp $SOOT_JARS:$JAVA_HOME_LIBS:. DataflowAnalysis.java

airbears2-10-142-37-169:java elenaglassman$ 
```

I'm assumed that was because I didn't have Java installed, but once I installed it (from here: https://www.java.com/en/download/mac_download.jsp) I still got:

```
airbears2-10-142-37-169:examplify elenaglassman$ JAVA_HOME_LIBS=`ls -d -1 $JAVA_HOME/jre/lib/*.jar | tr '\n' ':'`
ls: /jre/lib/*.jar: No such file or directory
```

Thoughts?

**Comment by eglassman** [comment]
I will also have Victor look at it with me. Seems like it's super debuggable, and I'm just mentally tired.

**Comment by andrewhead** [comment]
Ah, it looks like your JAVA_HOME isn't set!

Run this command.  Also, try putting it in your `~/.bash_profile` so it gets loaded in when you start your shell sessions:

```bash
export JAVA_HOME=`/usr/libexec/java_home -v 1.7`
```

**Comment by eglassman** [comment]
We made progress. However, we got stuck here:

```
airbears2-10-142-37-169:java elenaglassman$ javac -cp $SOOT_JARS:$JAVA_HOME_LIBS:. DataflowAnalysis.java
javac: invalid flag: /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/charsets.jar
Usage: javac <options> <source files>
use -help for a list of possible options
```

**Comment by andrewhead** [comment]
Can you share the value of your `SOOT_JARS` and `JAVA_HOME_LIBS` variables?  It looks to me like there might be a dash or a space somewhere in one of these variables, that's causing a path to a Java jar to look like a command line option, instead of the value to `-cp`

**Comment by eglassman** [comment]
Fixed!
