### ISSUE TITLE
What's the difference between these two classes?

### ISSUE THREAD

**Issue by eglassman** [andrewhead/examplify#5]
In `suggester/suggestion.coffee`:
```
module.exports.DeclarationSuggestion = class DeclarationSuggestion

  constructor: (name, type, symbol) ->
    @name = name
    @type = type
    @symbol = symbol

  getName: ->
    @name

  getType: ->
    @type

  getSymbol: ->
    @symbol
```

versus

in `error/missing-declaration.coffee`
```
module.exports.MissingDeclarationError = class MissingDeclarationError

  constructor: (symbol) ->
    @symbol = symbol

  getSymbol: ->
    @symbol
```

**Comment by andrewhead** [comment]
Good question!  To suggest a fix for a missing declaration, you need both the name and the type.  To fix the error, you need to add a line that looks like `<type> <name>;`.  For example, if I'm missing a declaration for a symbol `i` of type `int`, then the right line to add is:

```java
int i;
```

**Comment by andrewhead** [comment]
Looks like this is handled?  Let me know if we need to re-open it.
