### ISSUE TITLE
fix authorship that says Fresh Account

### ISSUE THREAD

**Issue by eglassman** [andrewhead/examplify#6]

**Comment by eglassman** [comment]
Instructions:
https://help.github.com/articles/changing-author-info/

**Comment by eglassman** [comment]
How I screwed things up:
http://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit

**Comment by andrewhead** [comment]
Probably can be closed as all of the work from the addingcontrollogic branch was cherry-picked into master.

**Comment by eglassman** [comment]
Yep
